### ISSUE TITLE
Create version of IBM Style guide

### ISSUE THREAD

**Issue by ChrisChinchilla** [testthedocs/vale-styles#7]
Inspiration from here

https://github.com/gaurav-nelson/retext-ibmstyleguide

**Comment by themr0c** [comment]
Could you create an `IBM` repository in the `testthedocs` namespace and add commit rights for @themr0c, @rkratky, @MichalMaler, @boczkowska, @robin-owen? All these people are working for Red Hat and have some interest in making the IBM Style guide for vale happen.

**Comment by infotexture** [comment]
See also https://github.com/errata-ai/IBM.

**Comment by ChrisChinchilla** [comment]
Closing in favour of the other repo, but I have no rights to it.
